# Generated by Django 4.2.3 on 2023-09-08 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('used_car', '0002_alter_usedcar_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='DOP'),
        ),
    ]
